# Generated by Django 3.0.6 on 2020-06-08 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='price',
        ),
    ]
